"""Email digest distribution for Axion."""

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

from src.config import get_settings

logger = logging.getLogger(__name__)


def send_digest_email(
    subject: str,
    body_html: str,
    body_text: str | None = None,
) -> bool:
    """
    Send a digest email to all configured recipients.

    Returns True if sent successfully, False otherwise.
    """
    settings = get_settings()
    email_cfg = settings.email

    if not email_cfg.enabled:
        logger.debug("Email not enabled — skipping digest email")
        return False

    if not email_cfg.to_addresses:
        logger.warning("No email recipients configured")
        return False

    if not email_cfg.smtp_user or not email_cfg.smtp_password.get_secret_value():
        logger.warning("SMTP credentials not configured")
        return False

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = email_cfg.from_address or email_cfg.smtp_user
    msg["To"] = ", ".join(email_cfg.to_addresses)

    if body_text:
        msg.attach(MIMEText(body_text, "plain"))
    msg.attach(MIMEText(body_html, "html"))

    try:
        if email_cfg.use_tls:
            server = smtplib.SMTP(email_cfg.smtp_host, email_cfg.smtp_port)
            server.starttls()
        else:
            server = smtplib.SMTP(email_cfg.smtp_host, email_cfg.smtp_port)

        server.login(email_cfg.smtp_user, email_cfg.smtp_password.get_secret_value())
        server.sendmail(
            email_cfg.from_address or email_cfg.smtp_user,
            email_cfg.to_addresses,
            msg.as_string(),
        )
        server.quit()
        logger.info("Digest email sent to %s", email_cfg.to_addresses)
        return True
    except Exception as e:
        logger.error("Failed to send digest email: %s", e, exc_info=True)
        return False


def format_digest_html(digest_data: dict) -> str:
    """Format a digest dict into an HTML email body."""
    sections = digest_data.get("sections", [])
    period_start = digest_data.get("period_start", "")
    period_end = digest_data.get("period_end", "")
    event_count = digest_data.get("event_count", 0)
    alert_count = digest_data.get("alert_count", 0)

    sections_html = ""
    for s in sections:
        title = s.get("title", "")
        content = s.get("content", "")
        if isinstance(content, list):
            items = "".join(f"<li>{_esc(str(item))}</li>" for item in content)
            content_html = f"<ul>{items}</ul>"
        elif isinstance(content, dict):
            items = "".join(
                f"<li><strong>{_esc(k)}:</strong> {_esc(str(v))}</li>"
                for k, v in content.items()
            )
            content_html = f"<ul>{items}</ul>"
        else:
            content_html = f"<p>{_esc(str(content))}</p>"
        sections_html += f"<h3 style='color:#2B579A;border-bottom:1px solid #ddd;padding-bottom:4px;'>{_esc(title)}</h3>{content_html}"

    return f"""
    <html>
    <body style="font-family:system-ui,-apple-system,sans-serif;color:#333;max-width:700px;margin:0 auto;">
        <div style="background:#2B579A;color:white;padding:16px 24px;border-radius:8px 8px 0 0;">
            <h1 style="margin:0;font-size:22px;">Axion Intelligence Digest</h1>
            <p style="margin:4px 0 0;opacity:0.8;font-size:13px;">
                {_esc(period_start)} — {_esc(period_end)} | {event_count} events | {alert_count} alerts
            </p>
        </div>
        <div style="padding:20px 24px;background:#fff;border:1px solid #e0e0e0;border-top:none;border-radius:0 0 8px 8px;">
            {sections_html or '<p>No sections available.</p>'}
        </div>
        <p style="font-size:11px;color:#999;text-align:center;margin-top:16px;">
            Generated by Axion Portfolio Intelligence — {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}
        </p>
    </body>
    </html>
    """


def format_digest_text(digest_data: dict) -> str:
    """Format a digest dict into plain text for email."""
    lines = ["AXION INTELLIGENCE DIGEST", "=" * 40, ""]
    period_start = digest_data.get("period_start", "")
    period_end = digest_data.get("period_end", "")
    lines.append(f"Period: {period_start} — {period_end}")
    lines.append(f"Events: {digest_data.get('event_count', 0)} | Alerts: {digest_data.get('alert_count', 0)}")
    lines.append("")

    for s in digest_data.get("sections", []):
        lines.append(s.get("title", "").upper())
        lines.append("-" * 30)
        content = s.get("content", "")
        if isinstance(content, list):
            for item in content:
                lines.append(f"  - {item}")
        elif isinstance(content, dict):
            for k, v in content.items():
                lines.append(f"  {k}: {v}")
        else:
            lines.append(f"  {content}")
        lines.append("")

    return "\n".join(lines)


def _esc(text: str) -> str:
    """Basic HTML escape."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
